version: "3.8"

services:
  backend:
    build:
      context: ./weather-backend  
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=${MONGO_URI}
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - HTTP_ADMIN_USER=${HTTP_ADMIN_USER}
      - HTTP_ADMIN_PASS=${HTTP_ADMIN_PASS}
    networks:
      - mynetwork
    command: npm run start
    depends_on:
      - db

  frontend:
    build:
      context: ./weather-frontend  
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    networks:
      - mynetwork
    command: npm run dev
    depends_on:
      - backend  

  db:
    image: mongo:latest  
    volumes:
      - .mongo-data:/data/db
    networks:
      - mynetwork
    ports:
      - "27017:27017"

networks:
  mynetwork:
    driver: bridge
